djangoshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from ecomapp.views import (
    base_view,
    category_view,
    product_view,
    cart_view,
    add_to_cart_view,
    remove_from_cart_view,
    change_item_qty,
    checkout_view,
    order_create_views,
    make_order_view,
    account_view,
    registration_view,
    login_view,
    notify_create,
    notify_delete
)

urlpatterns = [
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', category_view,
            name='category_detail'),
    re_path(r'^product/(?P<product_slug>[-\w]+)/$', product_view,
            name='product_detail'),
    re_path(r'^add_to_cart/$', add_to_cart_view,
            name='add_to_cart'),
    re_path(r'^remove_from_cart/$',
            remove_from_cart_view, name='remove_from_cart'),
    path('change_item_qty/', change_item_qty, name='change_item_qty'),
    path('cart/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('order/', order_create_views, name='create_order'),
    path('make_order/', make_order_view, name='make_order'),
    path('thank_you/', TemplateView.as_view(template_name="thank_you.html"),
         name='thank_you'),
    path('account/', account_view, name='account'),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='base'), name='logout'),
    path('', base_view, name='base'),
    path('notify_create/', notify_create, name='notify_create'),
    path('notify_delete/', notify_delete, name='notify_delete')
]

ecomapp/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.urls import reverse
from transliterate import translit
from decimal import Decimal
from django.contrib.auth.models import User
from django.conf import settings
from notifications.signals import notify


class Category(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(instance.name, reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=Category)

class Brand(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


def product_available_notification(sender, instance, *args, **kwargs):
    if instance.available:
        await_for_notify = [notification for notification in
                            MiddlewareNotification.objects.filter(
                                product=instance
                            )]
        for notification in await_for_notify:
            notify.send(
                instance,
                recipient=[notification.user_name],
                verb='Уважаемый {0}! {1}, который Вы ждете, поступил'.format(
                    notification.user_name.username,
                    instance.title),
                description=instance.slug
                )
            notification.delete()


post_save.connect(product_available_notification, sender=Product)


class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1) #кол-во
    item_total = models.DecimalField(max_digits=9, decimal_places=0, default=0)

    def __str__(self):
        return 'Cart item for product {0}'.format(self.product.title)


class Cart(models.Model): # корзина

    items=models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=0, default=0)

    def __str__(self):
        return str(self.id) # возвращает id корзины

    def add_to_cart(self, product_slug):
        cart=self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()

    def remove_from_cart(self, product_slug):
        cart=self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()

    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()

ORDER_STATUS_CHOISES = (
    ("Принят в обработку", "Принят в обработку"),
    ("Выполняется", "Выполняется"),
    ("Оплачен", "Оплачен")
)


class Order(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ForeignKey(Cart, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40,
                                   choices=(("Самовывоз", "Самовывоз"),
                                            ("Доставка", "Доставка")),
                                   default='Самовывоз'
                                   )
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOISES,
                              default=ORDER_STATUS_CHOISES[0][0])

    def __str__(self):
        return "Заказ №{0}".format(str(self.id))


class MiddlewareNotification(models.Model):

    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_notified = models.BooleanField(default=False)

    def __str__(self):
        return "Нотификация для пользователя {0} о поступлении товара {1}".format(self.user_name.username, self.product.title)

ecomapp/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.models import User


class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с данным логином не '
                                        'зарегистрирован в системе!')

        user = User.objects.get(username=username)
        if user and not user.check_password(password):
            raise forms.ValidationError('Неверный пароль!')


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_check = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'password_check',
            'first_name',
            'last_name',
            'email'
        ]

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['password'].help_text = 'Придумайте Пароль'
        self.fields['password_check'].label = 'Повторите Пароль'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['email'].label = 'Ваша почта'
        self.fields['email'].help_text = 'Пожалуйста, указывайте реальный адрес'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        password_check = self.cleaned_data['password_check']
        email = self.cleaned_data['email']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с данным логином уже '
                                        'зарегистрирован в системе!')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с данным почтовым '
                                        'адресом уже зарегистрирован!')
        if password != password_check:
            raise forms.ValidationError('Ваши пароли не совпадают! '
                                        'Попробуйте снова')






class OrderForm(forms.Form):

    name = forms.CharField()
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=([("self", "Самовывоз"),("delivery", "Доставка")]))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)


    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['phone'].label = 'Контактный телефон'
        self.fields['phone'].help_text = 'Пожалуйста, указывайте реальный ' \
                                         'номер телефона, по которому с ' \
                                         'Вами можно связаться'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Адрес доставки'
        self.fields['address'].help_text = '*Обязательно указывайте город!'
        self.fields['comments'].label = 'Коментарии к заказу'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Доставка производиться на ' \
                                        'следующий день после оформления ' \
                                        'заказа. Менеджер с Вами ' \
                                        'предварительно свяжеться'

ecomapp/templates/account.html
{% extends 'base.html' %}

{% block content %}

    <h3 class="text-center">Личный кабинет пользователя {{ request.user }}</h3>
    <hr>
    <h4 class="text-center">Ваши заказы</h4>
    <table class="table">
    <tr style='background: lightblue;'>
        <td class="text-center">Номер заказа</td>
        <td class="text-center">Дата заказа</td>
        <td class="text-center">Статус заказа</td>
        <td class="text-center">Стоимость заказа</td>
        <td class="text-center">Детали заказа</td>
        <td class="text-center"></td>
    </tr>
    {% for item in order %}
    <tr>
        <td class="text-center" style="padding-top: 20px; padding-bottom: 20px">{{ item.id }}</td>
        <td class="text-center" style="padding-top: 20px; padding-bottom: 20px">{{ item.date }}</td>
        <td class="text-center" style="padding-top: 20px; padding-bottom: 20px">{{ item.status }}</td>
        <td class="text-center" style="padding-top: 20px; padding-bottom: 20px">{{ item.total }} руб.</td>
        <td class="text-center" style="padding-top: 20px; padding-bottom: 20px"><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
    </tr>
    {% endfor %}
    </table>

<!-- Modal -->
{% for item in order %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Заказ № {{ item.id }}</h4>
      </div>
      <div class="modal-body">
      <h3>Товар</h3>
        <table class='table'>
        	{% for order_item in item.items.items.all %}
	        	<tr>
	       			<td>{{ order_item.product.title }}</td>
	       			<td>{{ order_item.qty }} шт.</td>
	       			<td>{{ order_item.item_total }} руб.</td>
	        	</tr>
        	{% endfor %}
        		 <tr>
	        		<td></td>
	        		<td>Итого</td>
	        		<td><strong>{{ item.items.cart_total }} руб.</strong></td>
	        	</tr>
        </table>
   		<h3>Заказчик</h3>
   		 <p>Имя: {{ item.first_name }}</p>
   		 <p>Фамилия: {{ item.last_name }}</p>
   		 <p>Телефон: {{ item.phone }}</p>
   		 <h3>Тип доставки</h3>
   		 <p>{% if item.buying_type == 'self' %} Самовывоз {% else %}Доставка{% endif %}</p>
   		 <p>{% if item.buying_type == 'delivery' %} {{ item.address }}{% endif %}</p>
   		 <h3>Комментарии к заказу</h3>
   		 <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

ecomapp/templates/base.html
{% load static %}
{% load notifications_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link rel='stylesheet' href='{% static "css/bootstrap.css" %}'>

    <!-- Custom CSS -->
    <link rel='stylesheet' href='{% static "css/shop-homepage.css" %}'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://127.0.0.1:8000">DjangoShop</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                {% if not request.get_full_path == '/' %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Категории<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for category in categories %}
                            <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                <li>
                <p class="navbar-text">Здравствуйте, гость!</p>
                </li>
                <li>
                    <a href="{% url 'login' %}">Войти</a>
                </li>
                <li>
                    <a href="{% url 'registration' %}">Регистрация</a>
                </li>
                {% else %}
                <li>
                    <p class="navbar-text">Здравствуйте, {{ request.user }}</p>
                </li>
                <li>
                    <a href="{% url 'account' %}">Личный кабинет</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Выйти</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Уведомления {% live_notify_badge badge_class="badge" %}</a>
                    <ul class="dropdown-menu" id="notifications-list">
                    {% live_notify_list %}
                    </ul>
                </li>
                 {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'cart' %}">Корзина <span class="badge" id="cart_count">{% if not request.session.total %} 0 {% else %}{{ request.session.total }} {% endif %}</span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}
        <div class="row">

            <div class="col-md-3">
                <p class="lead">Shop Name</p>
                <div class="list-group">
                    {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product in products %}
                                    {% if forloop.first %}
                                        <div class="item active">
                                            <img class="slide-image" src="{{ product.image.url }}" alt="" style=" padding-left: 175px; width: 80%; height: 400px">
                                            <br>
                                            <p class="text-center"><a href="{{ product.get_absolute_url }}"><button class="btn btn-primary">{{ product.title }}</button></a></p>
                                        </div>
                                    {% else %}
                                        <div class="item">
                                            <img class="slide-image" src="{{ product.image.url }}" alt="" style=" padding-left: 175px; width: 80%; height: 400px">
                                            <br>
                                            <p class="text-center"><a href="{{ product.get_absolute_url }}"><button class="btn btn-primary">{{ product.title }}</button></a></p>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev" style="background: transparent">
                                <span class="glyphicon glyphicon-chevron-left" style="color: black"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next" style="background: transparent">
                                <span class="glyphicon glyphicon-chevron-right" style="color: black"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail" style="height: 400px; position: relative">
                            <img src="{{ product.image.url }}" alt="" style='width:100%; height:250px;'>
                            <div class="caption">
                                <h4 class="text-center">{{product.price}} руб.</h4>
                                <p class='text-center'><strong><a href="{{product.get_absolute_url}}">{{product.title}}</a></strong></p>
                                </h5>
                                <div style='position: absolute; bottom: 0; right:52px;'>
                                {% if request.user.is_authenticated %}
                                    {% if product.available %}
                                    <p class='text-center'><a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>Добавить в корзину</button></a></p>
                                {% else %}
                                    <p class='text-center'><a href='{{ product.get_absolute_url }}'><button class='btn btn-info'>Товар отсутствует</button></a></p>
                                {% endif %}
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>

            </div>

        </div>
        {% endblock content %}
    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js" %}'></script>

    <script src='{% static "js/bootstrap.js" %}'></script>
    <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
    {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
<script>
$(document).ready(function(){
    $('.add_to_cart').on('click', function(e){
        e.preventDefault()
        product_slug = $(this).attr('data-slug')
        data = {
            product_slug: product_slug
        }
        $.ajax({
            type: "GET",
            url: '{% url "add_to_cart" %}',
            data: data,
            success: function(data){
                $("#cart_count").html(data.cart_total)
            }
        })
    })
})
</script>
<script>
    $(document).ready(function () {
        $('.live_notify_list').css('list-style-type', 'none')
        $('.live_notify_list').css('padding', '15px')
        $('.live_notify_list').css('width', '250px')
    })
</script>
<script>
    $(document).ready(function () {
        $('.dropdown').on('click', function () {
            $('#notifications-list').on('mouseenter', function () {
                $('#notification-active').on('mouseenter', function () {
                    var slug = $(this).attr('data-slug')

                    data = {
                        slug:slug
                    }

                    $.ajax({
                        type: "GET",
                        url: '{% url "notify_delete" %}',
                        data: data,
                        success: function (data) {
                            console.log('deleted')
                        }
                    })
                })
            })
        })
    })
</script>
</body>

</html>

ecomapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h3 class="text-center">Ваша корзина</h3>
    <br>
    {% if cart.items.count > 0 %}
    <div class="my-cart">
    <table class="table">
    <tr>
        <td class="text-center"><strong>Товар</strong></td>
        <td class="text-center"><strong>Кол-во</strong></td>
        <td class="text-center"><strong>Цена</strong></td>
        <td class="text-center"></td>
    </tr>
    {% for item in cart.items.all %}
    <tr class="cart-item-{{ item.product.id }}">
        <td class="text-center">{{ item.product.title }}</td>
        <td class="text-center">
            <form action="" method="GET">
                <input type="number" name="qty" class="cart-item-qty" data-id="{{ item.id }}" value="{{ item.qty }}" min="1" style="width: 40px;">
            </form>
        </td>
        <td class="text-center" id="cart-item-total-{{ item.id }}">{{ item.item_total }} руб.</td>
        <td class="text-center"><a href='#' class="remove_from_cart" data-slug="{{ item.product.slug }}" data-id="{{ item.product.id }}"><button class="btn btn-default">Удалить из корзины </button></a> </td>
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td class="text-center"><strong>Итого:</strong></td>
        <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} руб.</strong></td>
        <td class="text-center"></td>
    </tr>
    </table>
    <br>
    <a href="{% url 'checkout' %}" class="pull-right"><button class="btn btn-info">Предварительный заказ</button> </a>
    </div>
        <h3 class="cart-empty"></h3>
    {% else %}
    <h3 class="text-center">Ваша корзина пуста</h3>
    {% endif %}
    <script src='{% static "js/jquery.js" %}'></script>
    <script>
    $(document).ready(function () {
        $('.cart-empty').css('display', 'none')
        $('.remove_from_cart').on('click', function (e) {
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            item_product_id = $(this).attr('data-id')
            data = {
                product_slug: product_slug
            }

            $.ajax({
                type: "GET",
                url: '{% url 'remove_from_cart' %}',
                data: data,
                success: function (data) {
                    $('#cart_count').html(data.cart_total)
                    $('.cart-item-'+item_product_id).css('display', 'none')
                    $('#cart-total-price').html
                    ('<strong>' + parseFloat(data.cart_total_price) + ' руб. </strong>')
                    if (parseInt(data.cart_total) == 0){
                        $('.my-cart').css('display', 'none')
                        $('.cart-empty').css('display', 'block')
                        $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
                    }
                }
            })
        })
    })

    $(document).ready(function () {
        $('.cart-item-qty').on('click', function () {
            qty = $(this).val()
            item_id = $(this).attr('data-id')
            data = {
                qty: qty,
                item_id: item_id,
            }
            $.ajax({
                type: 'GET',
                url: '{% url "change_item_qty" %}',
                data: data,
                success: function (data) {
                    $('#cart-item-total-' + item_id).html
                    (parseFloat(data.item_total) + ' руб.')
                    $('#cart-total-price').html
                    ('<strong>' + parseFloat(data.cart_total_price) + ' руб. </strong>')
                }
            })
        })
    })
    </script>
{% endblock content %}

ecomapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Авторизация</h3>
<hr>
    <div class='col-sm-8 col-sm-offset-2'>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block" value="Войти в систему">
    </form>
    </div>


{% endblock content %}

ecomapp/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <form action="{% url 'make_order' %}" method="POST">
    {% csrf_token %}
    <div class="col-sm-4">
        {{ form.name|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.last_name|as_crispy_field }}
    </div>
    <div class="col-sm-4">
        {{ form.phone|as_crispy_field }}
    </div>
    {{ form.buying_type|as_crispy_field}}
    {{ form.address|as_crispy_field }}
    {{ form.date|as_crispy_field }}
    {{ form.comments|as_crispy_field }}
    <input type="submit" class="btn btn-success" value="Оформить заказ">
    </form>
    <script src='{% static "js/jquery.js" %}'></script>
    <script>
        $(document).ready(function () {
            $('#div_id_address').css('display', 'none')
            $('#id_buying_type').on('click', function () {
                buying_type = $(this).val()
                if (buying_type == 'delivery'){
                    $('#div_id_address').css('display', 'block')
                }else{
                    $('#div_id_address').css('display', 'none')
                }
            })
            $('#id_date_month').css('width', '120px')
            $('#id_date_month').css('display', 'inline')
            $('#id_date_year').css('width', '80px')
            $('#id_date_year').css('display', 'inline')
            $('#id_date_day').css('width', '70px')
            $('#id_date_day').css('display', 'inline')
        })
    </script>
{% endblock content %}

ecomapp/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center">Регистрация нового пользователя</h3>
    <div class="col-sm-8 col-sm-offset-2">
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block" value="Зарегистрироваться">
    </form>
    </div>

{% endblock content %}